"""Removed unecessary tables

Revision ID: 11721f64a8f6
Revises: 8f10deb70e7e
Create Date: 2025-04-21 08:54:36.916125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11721f64a8f6'
down_revision: Union[str, None] = '8f10deb70e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_hydration',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_daily_hydration_record_id'), 'daily_hydration', ['record_id'], unique=False)
    op.create_table('nutrition_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('water_goal_ml', sa.Integer(), nullable=False),
    sa.Column('fat_goal', sa.Integer(), nullable=False),
    sa.Column('protein_goal', sa.Integer(), nullable=False),
    sa.Column('carbs_goal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_column('daily_nutrition', 'protein_goal')
    op.drop_column('daily_nutrition', 'carbs_goal')
    op.drop_column('daily_nutrition', 'water_ml')
    op.drop_column('daily_nutrition', 'water_goal_ml')
    op.drop_column('daily_nutrition', 'daily_goal')
    op.drop_column('daily_nutrition', 'fat_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_nutrition', sa.Column('fat_goal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_nutrition', sa.Column('daily_goal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_nutrition', sa.Column('water_goal_ml', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_nutrition', sa.Column('water_ml', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_nutrition', sa.Column('carbs_goal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_nutrition', sa.Column('protein_goal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('nutrition_goals')
    op.drop_index(op.f('ix_daily_hydration_record_id'), table_name='daily_hydration')
    op.drop_table('daily_hydration')
    # ### end Alembic commands ###
