"""Combine DailyNutrition and DailyMacros

Revision ID: 8f10deb70e7e
Revises: a97a8ad404fb
Create Date: 2025-04-21 08:43:25.368629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f10deb70e7e'
down_revision: Union[str, None] = 'a97a8ad404fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for FK dependency ###
    op.drop_index('ix_daily_hydration_record_id', table_name='daily_hydration')
    op.drop_table('daily_hydration')

    op.drop_index('ix_daily_beverages_record_id', table_name='daily_beverages')
    op.drop_table('daily_beverages')

    op.drop_index('ix_beverage_types_beverage_id', table_name='beverage_types')
    op.drop_table('beverage_types')

    op.drop_index('ix_daily_macros_record_id', table_name='daily_macros')
    op.drop_table('daily_macros')

    op.add_column('daily_nutrition', sa.Column('water_ml', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('water_goal_ml', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('fat_consumed', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('fat_goal', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('protein_consumed', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('protein_goal', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('carbs_consumed', sa.Integer(), nullable=False))
    op.add_column('daily_nutrition', sa.Column('carbs_goal', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_nutrition', 'carbs_goal')
    op.drop_column('daily_nutrition', 'carbs_consumed')
    op.drop_column('daily_nutrition', 'protein_goal')
    op.drop_column('daily_nutrition', 'protein_consumed')
    op.drop_column('daily_nutrition', 'fat_goal')
    op.drop_column('daily_nutrition', 'fat_consumed')
    op.drop_column('daily_nutrition', 'water_goal_ml')
    op.drop_column('daily_nutrition', 'water_ml')
    op.create_table('daily_macros',
    sa.Column('record_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('fat_consumed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fat_goal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_consumed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_goal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carbs_consumed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carbs_goal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_macros_user_id_fkey'),
    sa.PrimaryKeyConstraint('record_id', name='daily_macros_pkey')
    )
    op.create_index('ix_daily_macros_record_id', 'daily_macros', ['record_id'], unique=False)
    op.create_table('daily_beverages',
    sa.Column('record_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('beverage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('servings', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume_ml', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverage_types.beverage_id'], name='daily_beverages_beverage_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_beverages_user_id_fkey'),
    sa.PrimaryKeyConstraint('record_id', name='daily_beverages_pkey')
    )
    op.create_index('ix_daily_beverages_record_id', 'daily_beverages', ['record_id'], unique=False)
    op.create_table('beverage_types',
    sa.Column('beverage_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('default_ml', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('beverage_id', name='beverage_types_pkey'),
    sa.UniqueConstraint('name', name='beverage_types_name_key')
    )
    op.create_index('ix_beverage_types_beverage_id', 'beverage_types', ['beverage_id'], unique=False)
    op.create_table('daily_hydration',
    sa.Column('record_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('water_ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('water_goal_ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_hydration_user_id_fkey'),
    sa.PrimaryKeyConstraint('record_id', name='daily_hydration_pkey')
    )
    op.create_index('ix_daily_hydration_record_id', 'daily_hydration', ['record_id'], unique=False)
    # ### end Alembic commands ###
