"""initial migration

Revision ID: a97a8ad404fb
Revises: 
Create Date: 2025-04-20 22:53:00.703055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97a8ad404fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beverage_types',
    sa.Column('beverage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('default_ml', sa.Integer(), nullable=True),
    sa.Column('default_calories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('beverage_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_beverage_types_beverage_id'), 'beverage_types', ['beverage_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('daily_beverages',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beverage_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverage_types.beverage_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_daily_beverages_record_id'), 'daily_beverages', ['record_id'], unique=False)
    op.create_table('daily_hydration',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('water_goal_ml', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_daily_hydration_record_id'), 'daily_hydration', ['record_id'], unique=False)
    op.create_table('daily_macros',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fat_consumed', sa.Integer(), nullable=False),
    sa.Column('fat_goal', sa.Integer(), nullable=False),
    sa.Column('protein_consumed', sa.Integer(), nullable=False),
    sa.Column('protein_goal', sa.Integer(), nullable=False),
    sa.Column('carbs_consumed', sa.Integer(), nullable=False),
    sa.Column('carbs_goal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_daily_macros_record_id'), 'daily_macros', ['record_id'], unique=False)
    op.create_table('daily_nutrition',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('consumed_calories', sa.Integer(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_daily_nutrition_record_id'), 'daily_nutrition', ['record_id'], unique=False)
    op.create_table('nutrition_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_affected', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_nutrition_history_history_id'), 'nutrition_history', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_history_history_id'), table_name='nutrition_history')
    op.drop_table('nutrition_history')
    op.drop_index(op.f('ix_daily_nutrition_record_id'), table_name='daily_nutrition')
    op.drop_table('daily_nutrition')
    op.drop_index(op.f('ix_daily_macros_record_id'), table_name='daily_macros')
    op.drop_table('daily_macros')
    op.drop_index(op.f('ix_daily_hydration_record_id'), table_name='daily_hydration')
    op.drop_table('daily_hydration')
    op.drop_index(op.f('ix_daily_beverages_record_id'), table_name='daily_beverages')
    op.drop_table('daily_beverages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_beverage_types_beverage_id'), table_name='beverage_types')
    op.drop_table('beverage_types')
    # ### end Alembic commands ###
