"""Add meal_name to DailyNutrition

Revision ID: eb286167a2c8
Revises: 11721f64a8f6
Create Date: 2025-04-21 09:37:38.365319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb286167a2c8'
down_revision: Union[str, None] = '11721f64a8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_nutrition', sa.Column('meal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_nutrition', 'meal_name')
    # ### end Alembic commands ###
